using System.Globalization;
using System.Resources;

namespace SpanDraft.Desktop.Resources;

public static class Strings
{
    public static string DeflectionDiagram => Get(nameof(DeflectionDiagram));
    public static string ShearDiagram => Get(nameof(ShearDiagram));
    public static string BendingDiagram => Get(nameof(BendingDiagram));
    public static string DiagramMinimum => Get(nameof(DiagramMinimum));
    public static string DiagramMaximum => Get(nameof(DiagramMaximum));
    public static string DiagramMinimumAndMaximum => Get(nameof(DiagramMinimumAndMaximum));
    public static string DiagramMinimumApproximate => Get(nameof(DiagramMinimumApproximate));
    public static string DiagramMaximumApproximate => Get(nameof(DiagramMaximumApproximate));
    public static string DiagramMinimumAndMaximumApproximate => Get(nameof(DiagramMinimumAndMaximumApproximate));
    public static string DistributedStartLabel => Get(nameof(DistributedStartLabel));
    public static string DistributedEndLabel => Get(nameof(DistributedEndLabel));
    public static string DistributedIntensityLabel => Get(nameof(DistributedIntensityLabel));
    public static string InvalidDistributedRange => Get(nameof(InvalidDistributedRange));
    public static string EntityNameLabel => Get(nameof(EntityNameLabel));
    public static string SchematicDrawing => Get(nameof(SchematicDrawing));
    public static string EmptyEntityName => Get(nameof(EmptyEntityName));
    public static string DuplicateEntityName => Get(nameof(DuplicateEntityName));
    private static readonly ResourceManager ResourceManager =
        new("SpanDraft.Desktop.Resources.Strings", typeof(Strings).Assembly);

    public static string ForceValueLabel => Get(nameof(ForceValueLabel));
    public static string MomentValueLabel => Get(nameof(MomentValueLabel));
    public static string InvalidLoadValue => Get(nameof(InvalidLoadValue));
    public static string LengthExcludesEntities => Get(nameof(LengthExcludesEntities));
    public static string Support => Get(nameof(Support));
    public static string SupportTypeLabel => Get(nameof(SupportTypeLabel));
    public static string Position => Get(nameof(Position));
    public static string OK => Get(nameof(OK));
    public static string Delete => Get(nameof(Delete));
    public static string SupportAlreadyExists => Get(nameof(SupportAlreadyExists));
    public static string PositionInsideBeam => Get(nameof(PositionInsideBeam));
    public static string LengthExcludesSupports => Get(nameof(LengthExcludesSupports));
    public static string InvalidSupportType => Get(nameof(InvalidSupportType));
    public static string SupportCoordinate => Get(nameof(SupportCoordinate));

    public static string SaveAs => Get(nameof(SaveAs));
    public static string Quit => Get(nameof(Quit));
    public static string Untitled => Get(nameof(Untitled));
    public static string ProjectFileFilter => Get(nameof(ProjectFileFilter));
    public static string ProjectFileError => Get(nameof(ProjectFileError));
    public static string ProjectFileMissing => Get(nameof(ProjectFileMissing));
    public static string ProjectBusy => Get(nameof(ProjectBusy));
    public static string LocalFilesOnly => Get(nameof(LocalFilesOnly));
    public static string LeaveQuestion => Get(nameof(LeaveQuestion));
    public static string DontSave => Get(nameof(DontSave));
    public static string RecoveryQuestion => Get(nameof(RecoveryQuestion));
    public static string RecoveryDamaged => Get(nameof(RecoveryDamaged));
    public static string RecoveryDiscardQuestion => Get(nameof(RecoveryDiscardQuestion));
    public static string RecoveryError => Get(nameof(RecoveryError));
    public static string Restore => Get(nameof(Restore));
    public static string Discard => Get(nameof(Discard));

    public static string RectangleSectionName => Get(nameof(RectangleSectionName));
    public static string RectangularHollowSectionName => Get(nameof(RectangularHollowSectionName));
    public static string CircleSectionName => Get(nameof(CircleSectionName));
    public static string CircularHollowSectionName => Get(nameof(CircularHollowSectionName));
    public static string CustomSectionName => Get(nameof(CustomSectionName));

    private static string Get(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture)
        ?? throw new MissingManifestResourceException(name);

    public static string ApplicationTitle => Get(nameof(ApplicationTitle));
    public static string File => Get(nameof(File));
    public static string Edit => Get(nameof(Edit));
    public static string View => Get(nameof(View));
    public static string Help => Get(nameof(Help));
    public static string Settings => Get(nameof(Settings));
    public static string NewProject => Get(nameof(NewProject));
    public static string EditProject => Get(nameof(EditProject));
    public static string Section => Get(nameof(Section));
    public static string Material => Get(nameof(Material));
    public static string CreateProject => Get(nameof(CreateProject));
    public static string Apply => Get(nameof(Apply));
    public static string Cancel => Get(nameof(Cancel));
    public static string Change => Get(nameof(Change));
    public static string BeamLength => Get(nameof(BeamLength));
    public static string PointForce => Get(nameof(PointForce));
    public static string Moment => Get(nameof(Moment));
    public static string DistributedLoad => Get(nameof(DistributedLoad));
    public static string FixedSupport => Get(nameof(FixedSupport));
    public static string PinnedSupport => Get(nameof(PinnedSupport));
    public static string RollerSupport => Get(nameof(RollerSupport));
    public static string BeamModel => Get(nameof(BeamModel));
    public static string OverviewLength => Get(nameof(OverviewLength));
    public static string OverviewPosition => Get(nameof(OverviewPosition));
    public static string Supports => Get(nameof(Supports));
    public static string Loads => Get(nameof(Loads));
    public static string Reactions => Get(nameof(Reactions));
    public static string Indicators => Get(nameof(Indicators));
    public static string MaximumDeflection => Get(nameof(MaximumDeflection));
    public static string GoverningMoment => Get(nameof(GoverningMoment));
    public static string MaximumBendingStress => Get(nameof(MaximumBendingStress));
    public static string SafetyFactorLabel => Get(nameof(SafetyFactorLabel));
    public static string OverviewName => Get(nameof(OverviewName));
    public static string OverviewType => Get(nameof(OverviewType));
    public static string OverviewValue => Get(nameof(OverviewValue));
    public static string CalculationUnavailable => Get(nameof(CalculationUnavailable));
    public static string SupportsMissing => Get(nameof(SupportsMissing));
    public static string InsufficientSupport => Get(nameof(InsufficientSupport));
    public static string IncompleteModel => Get(nameof(IncompleteModel));
    public static string CalculationNotPossible => Get(nameof(CalculationNotPossible));
    public static string CalculationComplete => Get(nameof(CalculationComplete));
    public static string InvalidLength => Get(nameof(InvalidLength));
    public static string SectionTemplateName => Get(nameof(SectionTemplateName));
    public static string SectionTemplateNote => Get(nameof(SectionTemplateNote));
    public static string MaterialTemplateNote => Get(nameof(MaterialTemplateNote));
    public static string SetupDescription => Get(nameof(SetupDescription));
    public static string EditLength => Get(nameof(EditLength));
    public static string Open => Get(nameof(Open));
    public static string Save => Get(nameof(Save));
    public static string Undo => Get(nameof(Undo));
    public static string Redo => Get(nameof(Redo));
    public static string Zoom => Get(nameof(Zoom));
    public static string About => Get(nameof(About));
    public static string AboutDescription => Get(nameof(AboutDescription));
    public static string VersionLabel => Get(nameof(VersionLabel));
    public static string GitHubLink => Get(nameof(GitHubLink));
    public static string LinkOpenError => Get(nameof(LinkOpenError));
    public static string LicenseOpenError => Get(nameof(LicenseOpenError));
    public static string SettingsTitle => Get(nameof(SettingsTitle));
    public static string SettingsUnits => Get(nameof(SettingsUnits));
    public static string ProfileMechanical => Get(nameof(ProfileMechanical));
    public static string ProfileStructural => Get(nameof(ProfileStructural));
    public static string ProfileUnitedStates => Get(nameof(ProfileUnitedStates));
    public static string ProfileCustom => Get(nameof(ProfileCustom));
    public static string UnitBeamLength => Get(nameof(UnitBeamLength));
    public static string UnitSectionDimension => Get(nameof(UnitSectionDimension));
    public static string UnitDeflection => Get(nameof(UnitDeflection));
    public static string UnitAxialDisplacement => Get(nameof(UnitAxialDisplacement));
    public static string UnitArea => Get(nameof(UnitArea));
    public static string UnitInertia => Get(nameof(UnitInertia));
    public static string UnitModulus => Get(nameof(UnitModulus));
    public static string UnitForce => Get(nameof(UnitForce));
    public static string UnitAxialForce => Get(nameof(UnitAxialForce));
    public static string UnitStress => Get(nameof(UnitStress));
    public static string UnitRotation => Get(nameof(UnitRotation));
    public static string SettingsNumeric => Get(nameof(SettingsNumeric));
    public static string PresentationStandard => Get(nameof(PresentationStandard));
    public static string PresentationDetailed => Get(nameof(PresentationDetailed));
    public static string PresentationStandardDescription => Get(nameof(PresentationStandardDescription));
    public static string PresentationDetailedDescription => Get(nameof(PresentationDetailedDescription));
    public static string PresentationCalculationHint => Get(nameof(PresentationCalculationHint));
    public static string SettingsLanguage => Get(nameof(SettingsLanguage));
    public static string InterfaceLanguage => Get(nameof(InterfaceLanguage));
    public static string SystemLanguage => Get(nameof(SystemLanguage));
    public static string LanguageUnavailable => Get(nameof(LanguageUnavailable));
    public static string SettingsDraftBlocked => Get(nameof(SettingsDraftBlocked));
    public static string SettingsSaveError => Get(nameof(SettingsSaveError));
}
